name: Submit Project for the Challenge
description: Use this form to submit your solution for feedback
title: "[Submission] Your_Project_Name"
labels: submission
body:
  - type: input
    id: participant_name
    attributes:
      label: Participant Name
      description: Enter your full name.
      placeholder: John Doe
  - type: input
    id: project_name
    attributes:
      label: Project Name
      description: Enter the name of the challenge you chose (e.g., Collaborative To-Do List App).
      placeholder: Collaborative To-Do List App
  - type: textarea
    id: project_description
    attributes:
      label: Project Description
      description: Provide a brief overview of your solution, its features, and any bonus features you included.
      placeholder: My app allows users to create shared to-do lists with priority sorting and progress tracking.
  - type: textarea
    id: challenges_encountered
    attributes:
      label: Challenges Faced
      description: Describe any challenges you faced while building your solution.
      placeholder: I struggled with implementing the sorting functionality and resolved it by using a conditional column.
  - type: markdown
    attributes:
      value: |
        ### 📎 Upload Your `.zip` File
        After submitting this form, attach your `.zip` file to this issue manually by dragging and dropping it into the comment box below.
        - Ensure your file is named as: `yourname_projectname.zip`.
        - Example: `john_doe_todolist.zip`.
